name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        env:
          VUE_APP_ALGOLIA_APPLICATION: ${{ secrets.VUE_APP_ALGOLIA_APPLICATION }}
          VUE_APP_ALGOLIA_API_KEY: ${{ secrets.VUE_APP_ALGOLIA_API_KEY }}
          VUE_APP_ALGOLIA_INDEX: ${{ secrets.VUE_APP_ALGOLIA_INDEX }}
          VUE_APP_BLOG_URL: ${{ secrets.VUE_APP_BLOG_URL }}
          VUE_APP_GITHUB_URL: ${{ secrets.VUE_APP_GITHUB_URL }}
        run: |
          npm run test:unit
          npm run test:e2e:ci
