name: test

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm ci
    - name: unit test
      env: 
        VUE_APP_ALGOLIA_APPLICATION: ${{ secrets.VUE_APP_ALGOLIA_APPLICATION }}
        VUE_APP_ALGOLIA_API_KEY: ${{ secrets.VUE_APP_ALGOLIA_API_KEY }}
        VUE_APP_ALGOLIA_INDEX: ${{ secrets.VUE_APP_ALGOLIA_INDEX }}
        VUE_APP_BLOG_URL: ${{ secrets.VUE_APP_BLOG_URL }}
        VUE_APP_GITHUB_URL: ${{ secrets.VUE_APP_GITHUB_URL }}
      run: npm run test:unit
    - name: e2e test
      uses: cypress-io/github-action@v1
      with:
        start: npm test:e2e
